limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;

server {
    listen       80;
    server_name  localhost;
    return 301 https://$host$request_uri;
}

server {
    listen       443 ssl;
    server_name  localhost;

    ssl_certificate     C:/nginx/certs/server.crt;
    ssl_certificate_key C:/nginx/certs/server.key;
    ssl_protocols       TLSv1.2 TLSv1.3;

    location / {
        return 200 "OK: static stub\n";
        add_header Content-Type text/plain;
    }

    location /api/ {
        limit_req zone=api_limit burst=5 nodelay;
        limit_req_status 429;

        alias C:/nginx/html/api/;
    	index index.html;
    }

    location /admin/ {
        auth_basic "Restricted Area";
        auth_basic_user_file C:/nginx/htpasswd;

        alias C:/nginx/html/admin/;
    	index index.html;
    }
}